name       : wraith-master
version    : 1.1.0
release    : 8
source     :
    - https://gitlab.com/serebit/wraith-master/-/archive/1.1.0/wraith-master-1.1.0.tar.gz : 1bd92cff6476f1486091f44764df0ecac629efc7040cfd9beee4cfbd76b3852a
    - https://download.jetbrains.com/kotlin/native/clang-llvm-8.0.0-linux-x86-64.tar.gz : a9ebf55170bdbe5e089dbf884e0bc52065b5b7bc52e9354415e25a36e10e56c5
    - https://download.jetbrains.com/kotlin/native/target-gcc-toolchain-3-linux-x86-64.tar.gz : ca25fc933fe45deb142f2672d3773227a65e652ebeb7bc6cc8425f747c5f8912
license    : Apache-2.0
component  : system.utils
summary    : GUI and command-line utility for controlling the RGB LEDs on AMD Wraith CPU coolers
description: |
    Wraith Master is a lightweight application for controlling the RGB LEDs on AMD's Wraith stock coolers. At the moment, the only supported cooler is the Wraith Prism, but there are plans to add other Wraith coolers as well. Both a command line interface and a graphical interface are provided.
networking : true
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libusb-1.0)
    - gradle
environment: |
    # prevents Gradle and Konan from failing to create files in ~
    export GRADLE_USER_HOME="$workdir/.gradle_home"
    export KONAN_DATA_DIR="$workdir/.konan_home"
setup      : |
    mkdir -p $KONAN_DATA_DIR/cache/
    cp $sources/*-linux-x86-64.tar.gz $KONAN_DATA_DIR/cache/
    cat $pkgfiles/gradle.properties >> gradle.properties
    gradle --refresh-dependencies
build      : |
    gradle package
install    : |
    gradle install -Ppackageroot=$installdir
