name       : wraith-master
version    : 1.2.0
release    : 13
source     :
    - https://gitlab.com/serebit/wraith-master/-/archive/v1.2.0/wraith-master-v1.2.0.tar.gz : 2644d588b3b773674a643e333ab262d6ea83d7d982e6de9895c41e980b00f0b8
    - https://download.jetbrains.com/kotlin/native/clang-llvm-8.0.0-linux-x86-64.tar.gz : a9ebf55170bdbe5e089dbf884e0bc52065b5b7bc52e9354415e25a36e10e56c5
    - https://download.jetbrains.com/kotlin/native/lldb-3-linux.tar.gz : 94240b9d7fdc72455af8472ce0088d3177a4840b409ec1b5e6be255ab20e4182
    - https://download.jetbrains.com/kotlin/native/x86_64-unknown-linux-gnu-gcc-8.3.0-glibc-2.19-kernel-4.9-2.tar.gz : a048397d50fb5a2bd6cc0f89d5a30e0b8ff0373ebff9c1d78ce1f1fb7f185a50
license    : Apache-2.0
component  : system.utils
homepage   : https://gitlab.com/serebit/wraith-master/
summary    : GUI and command-line utility for controlling the RGB LEDs on AMD Wraith CPU coolers
description: |
    Wraith Master is a lightweight application for controlling the RGB LEDs on AMD's Wraith stock coolers. At the moment, the only supported cooler is the Wraith Prism, but there are plans to add other Wraith coolers as well. Both a command line interface and a graphical interface are provided.
networking : true
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libusb-1.0)
    - gradle
    - kotlin-native
    - openjdk-17
    - scdoc
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH

    export KONAN_DATA_DIR="$workdir/.konan_home"
setup      : |
    mkdir -p $KONAN_DATA_DIR/dependencies/
    for FILE in $(find $sources -type f -not -name "wraith-master-*.tar.gz"); do
        tar -xf $FILE -C $KONAN_DATA_DIR/dependencies/
        echo $(basename -s .tar.gz $FILE) >> $KONAN_DATA_DIR/dependencies/.extracted
    done
build      : |
    export GRADLE_USER_HOME="$workdir/.gradle_home"
    %make \
        GRADLE=gradle \
        GRADLEFLAGS="-Pkotlin.native.home=/usr/share/kotlin-native"
install    : |
    %make_install \
        DESTDIR="$installdir" \
        PREFIX="/usr"
