name       : wraith-master
version    : 0.5.2
release    : 3
source     :
    - https://gitlab.com/serebit/wraith-master/-/archive/0.5.2/wraith-master-0.5.2.tar.gz : 8de383a1c09ecf5223d77edaf66977262fcbb288e46aee6469284e19535d4a80
    - https://download.jetbrains.com/kotlin/native/builds/releases/1.3.70/linux/kotlin-native-linux-1.3.70.tar.gz : 94b1fe4ad6831fcb72a2f8a0b3095eb323e9ba95736b3b5da43a07b60bfe603d
    - https://download.jetbrains.com/kotlin/native/clang-llvm-8.0.0-linux-x86-64.tar.gz : a9ebf55170bdbe5e089dbf884e0bc52065b5b7bc52e9354415e25a36e10e56c5
    - https://download.jetbrains.com/kotlin/native/target-gcc-toolchain-3-linux-x86-64.tar.gz : ca25fc933fe45deb142f2672d3773227a65e652ebeb7bc6cc8425f747c5f8912
license    : Apache-2.0
component  : system.utils
summary    : GUI and command-line utility for controlling the RGB LEDs on AMD Wraith CPU coolers
description: |
    Wraith Master is a lightweight application for controlling the RGB LEDs on AMD's Wraith stock coolers. At the moment, the only supported cooler is the Wraith Prism, but there are plans to add other Wraith coolers as well. Both a command line interface and a graphical interface are provided.
networking : true
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libusb-1.0)
    - openjdk-8
environment: |
    # prevents Gradle wrapper from failing to extract to ~/.gradle
    export GRADLE_USER_HOME=$workdir/.gradle
    # prevents Java from failing to create ~/.java
    export HOME=$workdir/.home
    # prevents Konan from failing to create ~/.konan
    export KONAN_DATA_DIR=$workdir/.konan
    # prevents Gradle from complaining about termcap info
    export TERM=xterm-256color
    # prevents Gradle from spawning daemons and never closing them
    export GRADLE_OPTS="-Dorg.gradle.daemon=false"
setup      : |
    mkdir -p $KONAN_DATA_DIR/cache/
    cp $sources/*-linux-x86-64.tar.gz $KONAN_DATA_DIR/cache/
    tar xzf $sources/kotlin-native-linux-*.tar.gz -C $KONAN_DATA_DIR
    ./gradlew --refresh-dependencies
build      : |
    ./gradlew package
install    : |
    ./gradlew install -Pinstalldir=$installdir/usr -Pudevdir=$installdir/usr/lib/udev
