name       : wraith-master
version    : 1.1.2
release    : 11
source     :
    - https://gitlab.com/serebit/wraith-master/-/archive/v1.1.2/wraith-master-v1.1.2.tar.gz : 6e85ef3beb794f077c4b0e80c9372ada14f55e0377afc9fdca440839766ba59f
    - https://download.jetbrains.com/kotlin/native/clang-llvm-8.0.0-linux-x86-64.tar.gz : a9ebf55170bdbe5e089dbf884e0bc52065b5b7bc52e9354415e25a36e10e56c5
    - https://download.jetbrains.com/kotlin/native/target-gcc-toolchain-3-linux-x86-64.tar.gz : ca25fc933fe45deb142f2672d3773227a65e652ebeb7bc6cc8425f747c5f8912
    - https://download.jetbrains.com/kotlin/native/lldb-3-linux.tar.gz : 94240b9d7fdc72455af8472ce0088d3177a4840b409ec1b5e6be255ab20e4182
license    : Apache-2.0
component  : system.utils
homepage   : https://gitlab.com/serebit/wraith-master/
summary    : GUI and command-line utility for controlling the RGB LEDs on AMD Wraith CPU coolers
description: |
    Wraith Master is a lightweight application for controlling the RGB LEDs on AMD's Wraith stock coolers. At the moment, the only supported cooler is the Wraith Prism, but there are plans to add other Wraith coolers as well. Both a command line interface and a graphical interface are provided.
networking : true
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libusb-1.0)
    - gradle
    - kotlin-native
environment: |
    export KONAN_DATA_DIR="$workdir/.konan_home"
setup      : |
    mkdir -p $KONAN_DATA_DIR/dependencies/
    for FILE in $(find $sources -type f -not -name "wraith-master-v%version%.tar.gz"); do
        tar -xzf $FILE -C $KONAN_DATA_DIR/dependencies/
        echo $(basename -s .tar.gz $FILE) >> $KONAN_DATA_DIR/dependencies/.extracted
    done
install    : |
    GRADLE_USER_HOME="$workdir/.gradle_home" gradle install \
        --no-daemon \
        --stacktrace \
        -Ppackageroot=$installdir \
        -Pkotlin.native.home=/usr/share/kotlin-native
